---
title: "Data Manipulation"
output: github_document
---

```{r setup}
library(tidyverse)
```

##load the FAS litters data

```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
litters_df
```

##select

choose some columns and not others

```{r}
select(litters_df, group, litter_number)
```
```{r}
select(litters_df, group, gd0_weight:gd_of_birth)
```
```{r}
select(litters_df, group, -litter_number)
```
renaming columns

```{r}
select(litters_df, GROUP = group, LITTer_NUmBer = litter_number)
```
```{r}
rename(litters_df, GROUP = group, LITTer_NUmBer = litter_number)
```

select helpers

```{r}
select(litters_df), starts_with("gd"))
```

```{r}
relocate(litters_df, litter_number)
```
## filter

```{r}
filter(litters_df, gd0_weight < 22)
```
```{r}
filter(litters_df, gd0_weight <= 22)
```

```{r}
filter(litters_df, gd_of_birth == 20)
```


```{r}
filter(litters_df, gd0_weight <= 22, gd_of_birth == 20)
```
```{r}
filter(litters_df, group == "Mod8")
```


```{r}
filter(litters_df, group %in% c("Con7, Mod8"))
```



##mutate




##arrange
```{r}
arrange(litters_df, pups_born_alive)
```

## %>%

```{r}
litters_data_raw = read_csv("./data/FAS_litters.csv")
litters_clean_name = janitor::clean_names(litters_data_raw)
litters_data_selected = select(litters_clean_name, -pups_survive)
litters_mutated = mutate(litters_data_selected, wt_gain = gd18_weight - gd0_weight)
```

USE THE PIPE OPERATOR INSTEAD

```{r}
litters_df =
  read_csv("./data/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  select(-pups_survive) %>% 
  drop_na(gd0_weight)
litters_df
```

